module.exports.REGULAR_BIKE_TRACKS_AVAILABLE = 4	
module.exports.REGULAR_CAR_TRACKS_AVAILABLE =2	 
module.exports.VIP_CAR_TRACKS_AVAILABLE  = 1	 
module.exports.REGULAR_SUV_TRACKS_AVAILABLE = 2	 
module.exports.VIP_SUV_TRACKS_AVAILABLE  = 1	